name: Deploy user_service to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: shoppcstore

      - name: Build Docker image and push to Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          gcloud builds submit ./src/user_service --tag asia-southeast1-docker.pkg.dev/shoppcstore/pc-store-repo/user_service

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy user-service \
            --image asia-southeast1-docker.pkg.dev/shoppcstore/pc-store-repo/user_service \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --port 8080
